"""Shared building blocks for every RipWatch contract model."""

from __future__ import annotations

from typing import Annotated

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field

# Crockford base32 ULID, as generated by rw.common.ids.
_ULID = r"[0-9A-HJKMNP-TV-Z]{26}"


def prefixed_id(prefix: str) -> str:
    """Regex for an ID of the form <prefix>_<ULID>."""
    return rf"^{prefix}_{_ULID}$"


ResultId = Annotated[str, Field(pattern=prefixed_id("res"))]
TraceId = Annotated[str, Field(pattern=prefixed_id("tr"))]
JobId = Annotated[str, Field(pattern=prefixed_id("job"))]
IncidentId = Annotated[str, Field(pattern=prefixed_id("inc"))]
DecisionId = Annotated[str, Field(pattern=prefixed_id("dec"))]

CameraId = Annotated[str, Field(pattern=r"^cam-[0-9]{2,}$")]
RipId = Annotated[str, Field(pattern=r"^cam-[0-9]{2,}-rip-[0-9]{4,}$")]
TrackId = Annotated[str, Field(pattern=r"^cam-[0-9]{2,}-sw-[0-9]{4,}$")]
S3Uri = Annotated[str, Field(pattern=r"^s3://[a-z0-9][a-z0-9.\-]{1,61}[a-z0-9]/.+$")]

Confidence = Annotated[float, Field(ge=0.0, le=1.0)]
UnitScore = Annotated[float, Field(ge=0.0, le=1.0)]
NonNegFloat = Annotated[float, Field(ge=0.0)]
NonNegInt = Annotated[int, Field(ge=0)]
Timestamp = AwareDatetime

# Default thresholds; the live values come from SSM /rw/vision/*_threshold
# and can be passed as validation context {"rip_threshold": .., "uncertain_threshold": ..}.
DEFAULT_RIP_THRESHOLD = 0.70
DEFAULT_UNCERTAIN_THRESHOLD = 0.40

MAX_POLYGON_POINTS = 32
MAX_KEYFRAMES = 10
MAX_MESSAGE_BYTES = 64 * 1024


class Contract(BaseModel):
    """Base for all contract models: unknown fields are rejected."""

    model_config = ConfigDict(extra="forbid", use_enum_values=False)
